#icinga2_manage_certs: force
#icinga2_master: true

mysql_databases:
  - name: icinga
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_users:
  - name: icinga
    host: "localhost"
    password: "{{ vault_icinga_mysql_user }}"
    priv: "icinga.*:ALL"
