---
- name: Setup Icinga 2 master certificate authoritie
  shell: "{{ icinga2_binary }} node setup --master --cn {{ icinga2_master_fqdn }}"
  when: icinga2_manage_certs == force
  register: icinga2.ca_ready

- name: Test config before restart Icinga 2
  shell: "{{ icinga2_binary }} daemon -C"
  register: icinga2.config_test
  when: icinga2.ca_ready.changed

- name: Restart Icinga 2 after master setup
  service:
    name: icinga2
    state: restarted
  when:
    - icinga2.ca_ready.changed
    - icinga2.config_test.rc == 0
