---
- name: setup ca
  include_role:
    name: icinga2-ansible/roles/icinga2-ca
  when:
    - icinga2.master == true
    - icinga2.manage_certs == 'force'

- name: generate ticket on the icinga master and save it as a variable
  shell: "{{ icinga2.binary }} pki ticket --cn {{ inventory_hostname }}"
  register: icinga2.client_ticket
  when:
    - (icinga2.client == true) or (icinga2.master == true)
    - icinga2.manage_certs == 'force'
  delegate_to: "{{ icinga2.master_fqdn }}"

- name: give ticket
  debug:
    msg: "{{ icinga2.client_ticket['stdout'] }}"
  when: icinga2.manage_certs == 'force'

- name: create pki folder on clients
  file:
    dest: /etc/icinga2/pki
    state: directory
    mode: 0700
    owner: icinga
    group: icinga
  when: icinga2.client == true

- name: create cert
  shell: |
    {{ icinga2.binary }} pki new-cert \
    --cn {{ inventory_hostname }} \
    --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
    --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
  when:
    - (icinga2.client == true) or (icinga2.master == true)
    - icinga2.manage_certs == 'force'

- name: save the masters cert as trustedcert
  shell: |
    {{ icinga2.binary }} pki save-cert \
    --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
    --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
    --trustedcert /etc/icinga2/pki/trusted-master.crt \
    --host {{ icinga2.master_fqdn }}
  when:
    - (icinga2.client == true) or (icinga2.master == true)
    - icinga2.manage_certs == 'force'

- name: request the certificate from the icinga server
  shell: |
    {{ icinga2.binary }} pki request \
    --host {{ icinga2.master_fqdn }} \
    --port {{ icinga2.api_port }} \
    --ticket {{ icinga2.client_ticket['stdout'] }} \
    --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
    --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
    --trustedcert /etc/icinga2/pki/trusted-master.crt --ca /etc/icinga2/pki/ca.key
  when:
    - (icinga2.client == true) or (icinga2.master == true)
    - icinga2.manage_certs == 'force'

- name: node setup
  shell: |
    {{ icinga2.binary }} node setup \
    --ticket {{ icinga2.client_ticket['stdout'] }} \
    --endpoint {{ icinga2.master_fqdn }} \
    --zone {{ inventory_hostname }} \
    --master_host {{ icinga2.master_fqdn }} \
    --trustedcert /etc/icinga2/pki/trusted-master.crt \
    --cn {{ inventory_hostname }} \
    --accept-commands \
    --accept-config
  when:
    - icinga2.client == true
    - icinga2.manage_certs == 'force'

# - name: Test config before restart Icinga 2
#   shell: "{{ icinga2_binary }} daemon -C"
#   register: icinga2_config_test

# - name: Restart Icinga 2 after node setup
#   service:
#     name: icinga2
#     state: restarted
#   when:
#     - icinga2_config_test.rc == 0
#     - icinga2_manage_certs == 'force'
