---
- name: include os family variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: setup ca
  include_role:
    name: icinga2-ansible/roles/icinga2-ca
  when:
    - icinga2_master == true
    - icinga2_manage_certs == 'force'

- name: generate ticket on the icinga master and save it as a variable
  shell: "{{ icinga2_binary }} pki ticket --cn {{ inventory_hostname }}"
  register: icinga2_client_ticket
  when:
    - (icinga2_client == true) or (icinga2_master == true)
    - icinga2_manage_certs == 'force'
  delegate_to: "{{ icinga2_master_fqdn }}"

- name: output ticket
  debug:
    msg: "{{ icinga2_client_ticket['stdout'] }}"
  when: icinga2_manage_certs == 'force'

- name: ensure certificate folder is present
  file:
    state: directory
    path: {{ icinga2_certs_directory }}
    owner: { icinga2_user }
    group: {{ icinga2_group }}

- name: create cert
  shell: |
    {{ icinga2_binary }} pki new-cert \
    --cn {{ inventory_hostname }} \
    --key {{ icinga2_certs_directory }}{{ inventory_hostname }}.key \
    --cert {{ icinga2_certs_directory }}{{ inventory_hostname }}.crt \
  when:
    - (icinga2_client == true) or (icinga2_master == true)
    - icinga2_manage_certs == 'force'

- name: save the masters cert as trustedcert
  shell: |
    {{ icinga2_binary }} pki save-cert \
    --key {{ icinga2_certs_directory }}{{ inventory_hostname }}.key \
    --cert {{ icinga2_certs_directory }}{{ inventory_hostname }}.crt \
    --trustedcert {{ icinga2_certs_directory }}trusted-master.crt \
    --host {{ icinga2_parent_host }}
  when:
    - (icinga2_client == true) or (icinga2_master == true)
    - icinga2_manage_certs == 'force'

- name: request the certificate from the icinga server
  shell: |
    {{ icinga2_binary }} pki request \
    --host {{ icinga2_master_fqdn }} \
    --port {{ icinga2_api_port }} \
    --ticket {{ icinga2_client_ticket['stdout'] }} \
    --key {{ icinga2_certs_directory }}{{ inventory_hostname }}.key \
    --cert {{ icinga2_certs_directory }}{{ inventory_hostname }}.crt \
    --trustedcert {{ icinga2_certs_directory }}trusted-master.crt --ca {{ icinga2_certs_directory }}ca.key
  when:
    - (icinga2_client == true) or (icinga2_master == true)
    - icinga2_manage_certs == 'force'

- name: node setup
  shell: |
    {{ icinga2_binary }} node setup \
    --ticket {{ icinga2_client_ticket['stdout'] }} \
    --endpoint {{ icinga2_parent_endpoint }} \
    --zone {{ inventory_hostname }} \
    --parent_zone {{ icinga2_parent_zone }} \
    --parent_host {{ icinga2_parent_host }} \
    --trustedcert {{ icinga2_certs_directory }}trusted-master.crt \
    --cn {{ inventory_hostname }} \
    --accept-commands \
    --accept-config \
    --disable-confd
  when:
    - icinga2_client == true
    - icinga2_manage_certs == 'force'

- name: Test config before restart Icinga 2
  shell: "{{ icinga2_binary }} daemon -C"
  register: icinga2_config_test

- name: Restart Icinga 2 after node setup
  service:
    name: icinga2
    state: restarted
  when:
    - icinga2_config_test.rc == 0
    - icinga2_manage_certs == 'force'
