---
- apt_key:
    url: "{{ icinga2.apt_repo.key }}"
    state: present
  when:
    - {{ icinga2.apt_repo.key }}
    - icinga2.manage_repos

- apt_repository:
    repo: "{{ icinga2.apt_repo.repo }}"
    state: present
    update_cache: yes
  when: icinga2.manage_repos

- name: install icinga 2 packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2
