---
- name:
  debug:
    msg: "{{ icinga2 }}"
    
- name: add icinga2 repository
  yum_repository:
    name: icinga-stable-release
    description: icinga2 latest repository
    baseurl: "{{ icinga2.yum_repo.baseurl }}"
    gpgkey: "{{ icinga2.yum_repo.gpgkey }}"
  when: icinga2.manage_repos


- name: install basic packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2
    - bash-completion
    - vim-icinga2
    - nagios-plugins-all
    - vim
