---
- name: add icinga2 repository
  yum_repository:
    name: icinga-stable-release
    description: icinga2 latest repository
    baseurl: {{ icinga2_yum.baseurl }}
    gpgkey: {{ icinga2_yum.gpgkey }}


- name: install basic packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2
    - bash-completion
    - vim-icinga2
    - nagios-plugins-all
    - vim
