---
- name: checking required variables for the module
  fail: msg=" "{{ item }}" should be defined!"
  when:
    - not {{ item }}
    - icinga2_master == true
  with_items:
    - icinga2_master_fqdn
    - icinga2_ido_engine


- include: install-Redhat.yml
  when: ansible_os_family == 'RedHat'

- include: install-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-ca.yml
  when: icinga2_master and icinga2_manage_certs == 'force'

- include: create-certificates.yml
  when: (icinga2_master == true) or
        (icinga2_client == true)

- include: manage-database.yml
  when:
    - icinga2_master == true
    - icinga2_ido_connection

- include: feature-handler.yml
  when:
    - icinga2_enabled_features
